[deps]
ClausenFunctions = "1cc96f36-ef02-40ef-a648-5e2c13df3076"
CollectiveSpins = "abf2e61e-3022-5fcf-a868-69d409dee72b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Noise = "81d43f40-5267-43b7-ae1c-8b967f377efa"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
QuantumCumulants = "35bcea6d-e19f-57db-af74-8011de6c7255"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"
QuantumOpticsBase = "4f57444f-1401-5e15-980d-4471b28d5678"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
